version: '3'
services:
  uptest:
    # image: h3rmt/uptest
    build: .
    ports:
      - 8080:8080
    volumes:
      - ./logs:/logs
      - ./responses:/responses
      # mount timezone file
      - /etc/localtime:/etc/localtime:ro
    environment:
      - URLS="www.google.com:google,www.yahoo.com:yahoo"
